In [1]:
#http://lpsolve.sourceforge.net/5.5/Python.htm#:~:text=lpsolve%20is%20callable%20from%20Python,so%20it%20has%20maximum%20performance.
from lpsolve55 import *
from lp_maker import *
import numpy as np
import pandas as pd
np.set_printoptions(suppress=True)

c=    [30, 40, 50, 35, 40, 30, 35, 25, 50, 45, 50] #cost vector
A=   [[1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],           #A matrix
      [1,   0,-1, 0, 0, 0, 0, 0, 0, 0, 0],
      [0,   0, 1,-1, 1, 0, 0, 0, 0, 0, 0],
      [0,   1, 0, 0, 0, 1, 0, 0, 1, 0, 0],
      [0,   0, 0, 1,-1,-1,-1, 1, 0, 1, 0],
      [0,   0, 0, 0, 0, 0, 1,-1, 0, 0, 1],
      [0,   0, 0, 0, 0, 0, 0, 0,1,1,1]]
dir=[-1,1,1,1,1,1,-1]  #Constraint Direction
b=[200,100,60,80,170,70,300] #RHS
lp = lp_maker(c, A, b, dir, None, setminim=1) #make lp, minimize
solvestat = lpsolve('solve', lp) #solve it
obj = lpsolve('get_objective', lp)
print(obj)
x = lpsolve('get_variables', lp)[0]
print(x)

22350.0
[120.0, 80.0, 19.99999999999999, 0.0, 40.00000000000001, 0.0, 0.0, 0.0, 0.0, 210.00000000000003, 69.99999999999999]

In [3]:
obj_sens=lpsolve('get_sensitivity_obj',lp)
                 
mydf=pd.DataFrame({'obj': x,'obj from': obj_sens[0],'obj to': obj_sens[1], 'obj till':obj_sens[2]}, 
                   index=['N_B', 'N_R', 'B_C', 'C_A', 'A_C', 'A_R', 'A_M', 'M_A', 'J_R', 'J_A', 'J_M'])
mydf.round(5)

       obj  obj from        obj to      obj till
N_B  120.0      25.0  3.500000e+01 -1.000000e+30
N_R   80.0      -5.0  4.500000e+01 -1.000000e+30
B_C   20.0      45.0  5.500000e+01 -1.000000e+30
C_A    0.0     -40.0  1.000000e+30 -1.000000e+30
A_C   40.0      35.0  4.500000e+01 -1.000000e+30
A_R    0.0      -0.0  1.000000e+30  4.000000e+01
A_M    0.0       5.0  1.000000e+30  7.000000e+01
M_A    0.0      -5.0  1.000000e+30  2.100000e+02
J_R    0.0      45.0  1.000000e+30  4.000000e+01
J_A  210.0      40.0  5.000000e+01 -1.000000e+30
J_M   70.0      20.0  8.000000e+01 -1.000000e+30

In [76]:
duals=lpsolve('get_sensitivity_rhs', lp)

mydf=pd.DataFrame({'duals': duals[0],'duals from': duals[1], 'duals till':duals[2]}, index=
    ['Nwk', 'Bstn', 'Clmbus', 'Rchmnd', 'Atl','Mbl', 'Jck','N_B', 'N_R', 'B_C', 'C_A', 'A_C', 
              'A_R', 'A_M', 'M_A', 'J_R', 'J_A', 'J_M'])
mydf.round(5)

        duals    duals from    duals till
Nwk      -5.0  1.800000e+02  2.400000e+02
Bstn     35.0  6.000000e+01  1.200000e+02
Clmbus   85.0  2.000000e+01  8.000000e+01
Rchmnd   45.0  4.000000e+01  1.000000e+02
Atl      45.0 -4.000000e+01  1.900000e+02
Mbl      50.0  0.000000e+00  9.000000e+01
Jck       0.0 -1.000000e+30  1.000000e+30
N_B       0.0 -1.000000e+30  1.000000e+30
N_R       0.0 -1.000000e+30  1.000000e+30
B_C       0.0 -1.000000e+30  1.000000e+30
C_A      75.0 -4.000000e+01  1.000000e+30
A_C       0.0 -1.000000e+30  1.000000e+30
A_R      30.0 -2.000000e+01  4.000000e+01
A_M      30.0 -2.100000e+02  7.000000e+01
M_A      30.0 -7.000000e+01  2.100000e+02
J_R       5.0 -2.000000e+01  4.000000e+01
J_A       0.0 -1.000000e+30  1.000000e+30
J_M       0.0 -1.000000e+30  1.000000e+30